### ISSUE TITLE
PyYAML ISSUE NOTE

### ISSUE THREAD

**Issue by jak010** [jak010/Mac-Tech-Note#1]
python3 -m pip install PyYAML
Defaulting to user installation because normal site-packages is not writeable
Collecting PyYAML
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/j4x6srgd6yb5ng8v9x1hqrj80000gn/T/pip-install-xl1vbf7k/pyyaml/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/j4x6srgd6yb5ng8v9x1hqrj80000gn/T/pip-install-xl1vbf7k/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cw/j4x6srgd6yb5ng8v9x1hqrj80000gn/T/pip-pip-egg-info-yxfb6ffg
         cwd: /private/var/folders/cw/j4x6srgd6yb5ng8v9x1hqrj80000gn/T/pip-install-xl1vbf7k/pyyaml/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by bluetoonist** [comment]
Mac에서 PyYAML을 pip로 설정할 떄 위와 같은 에러가 발생하는데 

python3 -m pip install -U pip setuptools 로 해결
